### ISSUE TITLE
Question: How do I enable hl-paren-mode globally

### ISSUE THREAD

**Issue by shankarpdy** [boyw165/hl-anything#10]
My emacs.el init file has this
         (hl-paren-mode 1)
But still, I have to execute hl-paren-mode to 1 in every buffer.

How can I globally enable this in all buffers and in all modes ?

**Comment by boyw165** [comment]
Well, `hl-paren-mode` is a buffer local minor mode and actually it support highlight of LISP enclosing parentheses. That's why it's not a global minor mode. If you want it global-like, you may try to add it to other mode's hook. For instance:

```lisp
;; Add hl-paren-mode to lisp-interaction-mode-hook.
(add-to-list 'lisp-interaction-mode-hook 'hl-paren-mode t)
```

I'm implementing the new way of it to give ability to support more languages. There's no clear roadmap since I have to finish some other features 1st.

**Comment by shankarpdy** [comment]
Thanks Wang.
This is sufficient for me to keep going.
Regards,
shankar


On Thu, Jan 22, 2015 at 9:44 AM, Boy Wang <notifications@github.com> wrote:

> Well, hl-paren-mode is a buffer local minor mode and actually it support
> highlight of LISP enclosing parentheses. That's why it's not a global minor
> mode. If you want it global-like, you may try to add it to other mode's
> hook. For instance:
>
> ;; Add hl-paren-mode to lisp-interaction-mode-hook.
> (add-to-list 'lisp-interaction-mode-hook 'hl-paren-mode t)
>
> I'm implementing the new way of it to give ability to support more
> languages. There's no clear roadmap since I have to finish some other
> features 1st.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boyw165/hl-anything/issues/10#issuecomment-70969111>.
>



-- 
Regards,
shankar

**Comment by hello-code** [comment]
`(add-to-list 'go-mode-hook 'hl-paren-mode t)`
Doesn't work in `go-mode`.

**Comment by tcw165** [comment]
Hello, what happened in `go-mode`?
